name: Multi-platform Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build_test_x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test

  build_test_aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker pull arm64v8/rust:latest
    - run: |
        docker run \
          --platform linux/arm64/v8 \
          -v $(pwd):/project \
          -w /project \
          arm64v8/rust \
          bash -c "cargo test"